name: CI-CD Common Pipeline

on:
  workflow_call:
    inputs:
      component:
        required: true
        type: string
      appType:
        required: true
        type: string
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: clean package
        if: ${{  inputs.appType == 'java' }}
        run: mvn clean package
      - name: upload artifact
        if: ${{  inputs.appType == 'java' }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{  inputs.component  }}-jar
          path: target/${{  inputs.component  }}-1.0.jar
          retention-days: 1
  test:
    runs-on: self-hosted
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo npm test
  docker:
    runs-on: self-hosted
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: download artifact
        if: ${{  inputs.appType == 'java' }}
        uses: actions/download-artifact@v4
        with:
          name: ${{  inputs.component  }}-jar
          path: ./
      - name: docker login
        run: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 389841108590.dkr.ecr.us-east-1.amazonaws.com
      - run: docker build -t 389841108590.dkr.ecr.us-east-1.amazonaws.com/${{  inputs.component  }} .
        name: docker build
      - run: docker push 389841108590.dkr.ecr.us-east-1.amazonaws.com/${{  inputs.component  }}
        name: docker build
  dev-deploy:
    runs-on: self-hosted
    environment: dev
    needs: docker
    steps:
      - uses: actions/checkout@v4
        with:
          repository: Sandeepkumar0088/roboshop-helm-charts-v1
#      - name: Configure AWS credentials
#        uses: aws-actions/configure-aws-credentials@v4
#        with:
#          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          aws-region: us-east-1
#
#      - name: Configure kubeconfig
#        run: |
#          aws eks update-kubeconfig --region us-east-1 --name dev
      - name: get kubectl config
        run: aws eks update-kubeconfig --name dev
#      - name: helm deploy app
#        run: helm upgrade -i ${{  inputs.component  }} . -f templates/${{  inputs.component  }}.yml --install --take-ownership --set apiVersion=${{ github.sha }}

      - name: argocd login
        run: |
          url=$(kubectl get svc argocd-server  -o jsonpath='{.status.loadBalancer.ingress[*].hostname}')
          argocd_password=$(kubectl get secrets argocd-initial-admin-secret -o jsonpath='{.data.password}' | base64 --decode)
          argocd login argocd-dev.sandeepkumar0088.online --insecure --username admin --password $argocd_password
      - name: Create App in ArgoCD
        run: argocd app create ${{ inputs.component }} --upsert --repo https://github.com/Sandeepkumar0088/roboshop-helm-charts-v1.git --path . --dest-namespace default --dest-server https://kubernetes.default.svc --grpc-web --helm-set appVersion=${{ github.sha }}
      - name: Sync App in ArgoCD
        run: argocd app sync ${{ inputs.component }} --grpc-web
      - name: ArgoCD App health Check
        run: argocd app wait ${{ inputs.component }} --grpc-web --timeout 120
  qa-deploy:
    runs-on: self-hosted
    needs: dev-deploy
    environment: qa
    steps:
      - uses: actions/checkout@v4
        with:
          repository: Sandeepkumar0088/roboshop-helm-charts-v1
      - name: get kubectl config
        run: echo aws eks update-kubeconfig --name qa
      - name: helm deploy app
        run: echo helm upgrade -i ${{  inputs.component  }} .

  uat-deploy:
    runs-on: self-hosted
    needs: qa-deploy
    environment: uat
    steps:
      - uses: actions/checkout@v4
        with:
          repository: Sandeepkumar0088/roboshop-helm-charts-v1
      - name: get kubectl config
        run: echo aws eks update-kubeconfig --name uat
      - name: helm deploy app
        run: echo helm upgrade -i ${{  inputs.component  }} . -f dev-values/${{  inputs.component  }}.yml

  prod-deploy:
    runs-on: self-hosted
    needs: uat-deploy
    environment: prod
    steps:
      - uses: actions/checkout@v4
        with:
          repository: Sandeepkumar0088/roboshop-helm-charts-v1
      - name: echo get kubectl config
        run: echo aws eks update-kubeconfig --name prod
      - name: helm deploy app
        run: echo helm upgrade -i ${{  inputs.component  }} . -f dev-values/${{  inputs.component  }}.yml